version: "3.9"

services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./RabbitMq/Config/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf:ro
      - ./RabbitMq/Config/definitions.json:/etc/rabbitmq/definitions.json:ro
