@MicroOrder.ProductService.API_HostAddress = https://localhost:7215

GET {{MicroOrder.ProductService.API_HostAddress}}/api/products
Content-Type: application/json

###

POST {{MicroOrder.ProductService.API_HostAddress}}/api/products
Content-Type: application/json

{
    "name": "Product 4",
    "price": 10.40,
    "quantity": 7
}

###

POST {{MicroOrder.ProductService.API_HostAddress}}/api/products/check-availability
Content-Type: application/json

{
    "products": [
        {
            "id": "065e5abd-56f7-43c9-e5f2-08dd738c77f6",
            "quantity": 1
        },
        {
            "id": "c5896807-6dcb-4629-7522-08dd73717ddf",
            "quantity": 101
        }
    ]
}

###

GET {{MicroOrder.ProductService.API_HostAddress}}/api/products/{productId}

###
